### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by vcoyne1** [jdrudolph/PerseusR#6]
Running install_github('jdrudolph/PerseusR') in order to install in R 3.5.1 results in the following error:
Error in read.dcf(path) : 
  Found continuation line starting '    R (>= 3.3.0) ...' at begin of record.

Not sure how to rectify.

**Comment by jdrudolph** [comment]
I could not reproduce the error you are describing and I don't believe that it is specific to `PerseusR`.
A google search for the error message seems to point towards a more general issue with installing packages. Did you succeed in installing any other R packages via CRAN?

**Comment by jdrudolph** [comment]
@vcoyne1 Could you please report the output of `sessionInfo()` or more specifically, which version of the `devtools` library you are using.
I just had the same error as you installing `PerseusR` on a windows machine. Installing `devtools_1.13.6` instead of `devtools_2.0.0` solved the issue. I did that by running

    install.packages('devtools', type='binary')
    library('devtools')
    install_github('jdrudolph/PerseusR')

**Comment by vcoyne1** [comment]
> @vcoyne1 Could you please report the output of `sessionInfo()` or more specifically, which version of the `devtools` library you are using.
> I just had the same error as you installing `PerseusR` on a windows machine. Installing `devtools_1.13.6` instead of `devtools_2.0.0` solved the issue. I did that by running
> 
> ```
> install.packages('devtools', type='binary')
> library('devtools')
> install_github('jdrudolph/PerseusR')
> ```

Thanks! I also had devtools_2.0.0 installed. I uninstalled and replaced with devtools_1.13.6 and the problem is now resolved.
